apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - image: nyeve/capstone:latest
          imagePullPolicy: Always
          name: nodeapp
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP